### ISSUE TITLE
align_start_time Not Supported in Kairos before 0.94

### ISSUE THREAD

**Issue by gwittel** [Kratos-ISE/grafana-kairosdb-datasource-plugin#5]
The addition of ```align_start_time``` breaks if using Kairos 0.93 and probably sooner.  The parameter was added in Kairos 0.94.  I did a quick and dirty fix (default parameter to false, only supply when set to true; see -- gwittel/grafana-kairosdb-datasource-plugin@7a0a5b32a989b3bff9d676fb838406e5fb5c1188);  but the better thing might to somehow map a config setting (like Kairos version) to map what parameters are/aren't supported.

I haven't dug into this a lot; just ran into the problem with some older KairosDB instances we have around.  Given the quick/dirty nature of the fix I wasn't comfortable with making it into a PR.

**Comment by rdettai** [comment]
Thanks for the feedback. Its weird because I was pretty sure this parameter was available in 0.9.3... But maybe there are different versions within that release.  I'll check it a bit later. Your solution seems interesting!

**Comment by rdettai** [comment]
I've done something very close to what you did, except that I left align_start_time checked as default. If you want to be compatible with an older version of Kairos you just have to uncheck it.
Kratos-ISE/grafana-kairosdb-datasource-plugin@21277b656c6b77dfbe9ec8e5bdcb94a447d269b1
