### ISSUE TITLE
console is undefined in IE 8/9 with closed Dev Tools

### ISSUE THREAD

**Issue by hschwarz72** [Kratos-ISE/grafana-kairosdb-datasource-plugin#6]
As IE 8/9 (and maybe other IE versions as well) do not define the console object if the development tools are not open there is a javascript error while displaying data.

The critical line is (among some other console log output for error output):
console.log("sample_size:" + sample_size + " samples");

**Comment by rdettai** [comment]
I commented out the console log, they are mostly irrelevant anyway. Thanks for your feedback!
